version: '3.10'

services:

    #   SERVIÇO DE CACHE
    redis:
        container_name: blog_redis
        build: ./redis/
        restart: always
        privileged: true
        volumes:
            - redis:/var/lib/redis
        env_file:
            - .env
        ports:
            - "6379:6379"
        networks:
            - blog_network

    #   SERVIDOR HTTP
    nginx:
        container_name: blog_nginx
        build: ./nginx/
        restart: always
        volumes:
            - nginx:/var/lib/nginx
        env_file:
            - .env
        ports:
            - "8080:80"
        networks:
            - blog_network
            
volumes:
    redis:
        driver: local
    nginx:
        driver: local

networks:
    blog_network:
        driver: bridge