version: '3.10'

services:

    #   SERVIÇO DE CACHE
    redis:
        container_name: blog_redis
        build: ./redis/
        restart: always
        volumes:
            - redis:/var/lib/redis
        env_file:
            - .env
        ports:
            - "6379:6379"
        networks:
            - blog_network
        privileged: true

    #   SERVIDOR HTTP
    nginx:
        container_name: blog_nginx
        build: ./nginx/
        restart: always
        volumes:
            - nginx:/var/lib/nginx
        env_file:
            - .env
        ports:
            - "8080:80"
        networks:
            - blog_network
        
    #   MESSAGE BROKER
    rabbitmq:
        container_name: blog_rabbitmq
        build: ./rabbitmq/
        restart: always
        volumes:
            - rabbitmq:/var/lib/rabbitmq
        env_file:
            - .env
        ports:
            - 25672:25672   #   NÓS RABBITMQ E A FERRAMENTA CLI
            - 15672:15672   #   API WEB DE GERENCIAMENTO COM O HOST
        networks:
            - blog_network
            
volumes:
    redis:
        driver: local
    nginx:
        driver: local
    rabbitmq:
        driver: local

networks:
    blog_network:
        driver: bridge